"""Upgrade the 550M notebook's corpus to a higher-quality, Qwen-style English mix.

Keeps everything else in the notebook untouched; only cell 3 (corpus) is rewritten:
  wikipedia (encyclopedic, ~4 GB)
  + cosmopedia 'web_samples_v2' (synthetic textbooks/educational, ~2 GB)
  + finemath 'finemath-4plus' (curated math/reasoning, ~0.5 GB)
  + codeparrot-clean (Python code, ~1.5 GB)
  -- TinyStories (child-level) removed
"""
import json, urllib.request

URL = 'https://raw.githubusercontent.com/samratbarman1013-commits/transformer-llm/main/notebooks/train_500m_colab.ipynb'
with urllib.request.urlopen(URL) as r:
    nb = json.loads(r.read().decode())


def set_src(cell, text):
    lines = text.split('\n')
    if lines[-1]:
        cell['source'] = [l + '\n' for l in lines[:-1]] + [lines[-1]]
    else:
        cell['source'] = [l + '\n' for l in lines[:-1]]


NEW_C3 = r'''#@title 3 - Corpus (high-quality English mix ~8 GB - skipped if already on Drive)
import subprocess, sys, os, json, gzip, urllib.request
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'datasets'], check=True)

DATA = '/content/data'
os.makedirs(DATA, exist_ok=True)
CORPUS = f'{DATA}/corpus.txt'
NL = chr(10)

if os.path.exists(f'{DRIVE}/bins/train.bin'):
    print('corpus already prepared on Drive - nothing to download')
elif os.path.exists(CORPUS) and os.path.getsize(CORPUS) > 5_000_000_000:
    print('corpus.txt present:', round(os.path.getsize(CORPUS)/1e9, 2), 'GB')
else:
    if os.path.exists(CORPUS):
        print('incomplete corpus found (', round(os.path.getsize(CORPUS)/1e9, 2), 'GB) - redownloading')
    with open(CORPUS, 'w', encoding='utf-8') as out:
        from datasets import load_dataset

        def stream_texts(ds, cap, label):
            n, last = 0, 0
            for ex in ds:
                t = (ex.get('text') or '').strip()
                if len(t) < 200:
                    t = ((ex.get('problem') or '') + ' ' + (ex.get('solution') or '')).strip()
                    if len(t) < 200:
                        continue
                out.write(t + NL); n += len(t) + 1
                if n >= cap:
                    break
                if n - last >= 500_000_000:
                    last = n; print(f'  {label}:', round(n/1e9, 2), 'GB downloaded')
            print(f'{label}:', round(n/1e9, 2), 'GB')

        # 1) English Wikipedia - encyclopedic reference text (~4 GB)
        print('downloading wikipedia (4 GB)... progress every 0.5 GB below')
        stream_texts(load_dataset('wikimedia/wikipedia', '20231101.en', split='train', streaming=True),
                     4_000_000_000, 'wikipedia')
        # 2) Cosmopedia - synthetic textbooks/educational text, high quality (~2 GB)
        print('downloading cosmopedia (2 GB)... a few quiet minutes')
        stream_texts(load_dataset('HuggingFaceTB/cosmopedia', 'web_samples_v2', split='train', streaming=True),
                     2_000_000_000, 'cosmopedia')
        # 3) FineMath - curated math/reasoning text (~0.5 GB)
        print('downloading finemath (0.5 GB)... a few quiet minutes')
        stream_texts(load_dataset('HuggingFaceTB/finemath', 'finemath-4plus', split='train', streaming=True),
                     500_000_000, 'finemath')
        # 4) Python code (~1.5 GB) from codeparrot-clean
        cap, n = 1_500_000_000, 0
        for i, shard in enumerate(('file-000000000001.json.gz', 'file-000000000002.json.gz'), 1):
            print(f'downloading python code shard {i}/2 (~1 GB)... a few quiet minutes')
            path = f'{DATA}/{shard}'
            urllib.request.urlretrieve(
                f'https://huggingface.co/datasets/codeparrot/codeparrot-clean/resolve/main/{shard}', path)
            with gzip.open(path, 'rt', encoding='utf-8', errors='ignore') as f:
                for line in f:
                    try:
                        ex = json.loads(line)
                    except Exception:
                        continue
                    c = ex.get('content') or ''
                    if len(c) < 200 or ex.get('autogenerated'):
                        continue
                    out.write(c + NL); n += len(c) + 1
                    if n >= cap:
                        break
            os.remove(path)
            if n >= cap:
                break
        print('python code:', round(n/1e9, 2), 'GB')
print('corpus ready')
'''

c3 = ''.join(nb['cells'][3]['source'])
assert 'wikimedia/wikipedia' in c3, 'cell 3 is not the expected corpus cell'
assert 'TinyStories' in c3, 'TinyStories block not found - notebook changed'
set_src(nb['cells'][3], NEW_C3)

c0 = ''.join(nb['cells'][0]['source'])
assert 'English Wikipedia' in c0, 'cell 0 markdown unexpected'
c0 = c0.replace('English Wikipedia', 'high-quality English mix (Wikipedia + Cosmopedia + FineMath + code)')
set_src(nb['cells'][0], c0)

out = json.dumps(nb, indent=1)
assert 'cosmopedia' in out and 'finemath' in out and 'TinyStories' not in out, 'corpus swap failed'
open('notebooks/train_500m_colab.ipynb', 'w').write(out)
print('notebook rebuilt with high-quality English corpus mix')
